
package pizza.cashier.interference;

import SQLinfo.Information;
import information.accountsAndOrders;
import java.sql.*;

/**
 *
 * @author s_che
 */

public class changeMangAcc extends javax.swing.JFrame {
    
    private boolean isPassword;
    static ResultSet rs;
    static ResultSetMetaData rsmd;
    /**
     * Creates new form changeMangAcc
     */
    public changeMangAcc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane = new javax.swing.JLayeredPane();
        jPanel = new javax.swing.JPanel();
        CurrentAccInfoTxt = new javax.swing.JTextField();
        currentUsernameTxt = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        btnEditUsername = new javax.swing.JButton();
        currentPasswordTxt = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        btnEditPassword = new javax.swing.JButton();
        btnViewPassword = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        setNewUserOrPassTxt = new javax.swing.JTextField();
        instructionsSetNewInfo = new javax.swing.JLabel();
        enterNewUserOrPass = new javax.swing.JTextField();
        errorTxt = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLayeredPane.setLayout(new java.awt.CardLayout());

        jPanel.setBackground(new java.awt.Color(204, 204, 255));

        CurrentAccInfoTxt.setEditable(false);
        CurrentAccInfoTxt.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        CurrentAccInfoTxt.setText("Current Account Information");
        CurrentAccInfoTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 0, 0)));
        CurrentAccInfoTxt.setSelectionColor(new java.awt.Color(204, 102, 0));

        currentUsernameTxt.setEditable(false);
        currentUsernameTxt.setText(accountsAndOrders.getManagerAcc().getUsername());

        usernameLabel.setText("<html><u>Username:</u></html>");

        btnEditUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/editIcon.png"))); // NOI18N
        btnEditUsername.setBorder(null);
        btnEditUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUsernamebtnEditUsernameActionPerformed(evt);
            }
        });

        currentPasswordTxt.setEditable(false);
        currentPasswordTxt.setText(setPasswordTxtToStars());

        passwordLabel.setText("<html><u>Password:</u></html>");

        btnEditPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/editIcon.png"))); // NOI18N
        btnEditPassword.setBorder(null);
        btnEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPasswordActionPerformed(evt);
            }
        });

        btnViewPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/viewIcon.png"))); // NOI18N
        btnViewPassword.setBorder(null);
        btnViewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPasswordbtnViewPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(CurrentAccInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usernameLabel)
                            .addComponent(passwordLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(currentPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(btnViewPassword))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(currentUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditPassword)
                            .addComponent(btnEditUsername))
                        .addGap(6, 6, 6)))
                .addGap(44, 44, 44))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(CurrentAccInfoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(currentUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameLabel)))
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(currentPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnViewPassword))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jLayeredPane.add(jPanel, "card2");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        setNewUserOrPassTxt.setEditable(false);
        setNewUserOrPassTxt.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 24)); // NOI18N
        setNewUserOrPassTxt.setText("Set New Username");
        setNewUserOrPassTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 0, 0)));
        setNewUserOrPassTxt.setSelectionColor(new java.awt.Color(204, 102, 0));

        instructionsSetNewInfo.setText("Enter your new desired username below.");

        enterNewUserOrPass.setText("Type here...");

        errorTxt.setForeground(new java.awt.Color(153, 0, 0));
        errorTxt.setText(" ");

        btnGo.setText("GO");
        btnGo.setBorder(null);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/returnIcon.png"))); // NOI18N
        btnReturn.setBorder(null);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnbtnEditUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(instructionsSetNewInfo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(setNewUserOrPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(btnReturn))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(enterNewUserOrPass, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(setNewUserOrPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructionsSetNewInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterNewUserOrPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(errorTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jLayeredPane.add(jPanel1, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void switchCardPanel(javax.swing.JPanel panel) {
        jLayeredPane.removeAll();
        jLayeredPane.add(panel);
        jLayeredPane.revalidate();
        jLayeredPane.repaint();
    }
    
    private void btnEditUsernamebtnEditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUsernamebtnEditUsernameActionPerformed
        switchCardPanel(jPanel1);
    }//GEN-LAST:event_btnEditUsernamebtnEditUsernameActionPerformed

    private void btnViewPasswordbtnViewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPasswordbtnViewPasswordActionPerformed
        if(btnViewPassword.isSelected()) {
            currentPasswordTxt.setText(accountsAndOrders.getManagerAcc().getPassword());
        } else {
            currentPasswordTxt.setText(setPasswordTxtToStars());
        }
    }//GEN-LAST:event_btnViewPasswordbtnViewPasswordActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        boolean containsSpace = enterNewUserOrPass.getText().trim().contains(" ");
        
        if(containsSpace) {
            errorTxt.setText("No spaces are allowed. Please use valid characters.");
        } else {
            if(isPassword) {
            accountsAndOrders.getManagerAcc().setPassword(enterNewUserOrPass.getText());
            
            try(Connection conn = DriverManager.getConnection(Information.getUrlSQL(), Information.getUsernameSQL(), Information.getPasswordSQL())) {
                Statement statement = conn.createStatement();
                statement.executeUpdate("UPDATE `foods`.`manageracc` SET `password` = '" + enterNewUserOrPass.getText() + "' WHERE (`id-manager` = '1');");
            } catch(Exception ex) {System.out.println(ex);}
            
            isPassword = false;
            } else {
                accountsAndOrders.getManagerAcc().setUsername(enterNewUserOrPass.getText());
                
                try ( Connection conn = DriverManager.getConnection(Information.getUrlSQL(), Information.getUsernameSQL(), Information.getPasswordSQL())) {
                    Statement statement = conn.createStatement();
                    statement.executeUpdate("UPDATE `foods`.`manageracc` SET `username` = '" + enterNewUserOrPass.getText() + "' WHERE (`id-manager` = '1');");
                } catch (Exception ex) {System.out.println(ex);}
                
                currentUsernameTxt.setText(accountsAndOrders.getManagerAcc().getUsername());
            }
            enterNewUserOrPass.setText("Type here...");
            currentPasswordTxt.setText(setPasswordTxtToStars());
            errorTxt.setText(" ");
            
            switchCardPanel(jPanel);
        }
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnReturnbtnEditUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnbtnEditUsernameActionPerformed
        enterNewUserOrPass.setText("Type here...");
        errorTxt.setText(" ");
        switchCardPanel(jPanel);
    }//GEN-LAST:event_btnReturnbtnEditUsernameActionPerformed

    private void btnEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPasswordActionPerformed
        isPassword = true;
        switchCardPanel(jPanel1);
        setNewUserOrPassTxt.setText("Set New Password");
        instructionsSetNewInfo.setText("Enter your new desired password below.");
    }//GEN-LAST:event_btnEditPasswordActionPerformed
    
    public String setPasswordTxtToStars() {
        String stars = "";
        for(int i = 0; i < accountsAndOrders.getManagerAcc().getPassword().length(); i++) {
            stars += "*";
        }
        return stars;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentAccInfoTxt;
    private javax.swing.JButton btnEditPassword;
    private javax.swing.JButton btnEditUsername;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnReturn;
    private javax.swing.JToggleButton btnViewPassword;
    private javax.swing.JTextField currentPasswordTxt;
    private javax.swing.JTextField currentUsernameTxt;
    private javax.swing.JTextField enterNewUserOrPass;
    private javax.swing.JLabel errorTxt;
    private javax.swing.JLabel instructionsSetNewInfo;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField setNewUserOrPassTxt;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
