package pizza.cashier.interference;

import SQLinfo.Information;
import information.*;
import java.sql.*;

public class loginPage extends javax.swing.JFrame {

    static ResultSet rs;
    static ResultSetMetaData rsmd;
    static int numAccs = 0;
    static int numCAccs = 0;
    /**
     * Creates new form loginPage
     */
    public loginPage() {
        connectDB(Information.getUrlSQL(), Information.getUsernameSQL(), Information.getPasswordSQL());
        initComponents();
        loginError.setVisible(false); //making sure login error message isn't seen (until there is an actual error)
    }
    
    public static void connectDB(String url, String username, String password) {
        try ( Connection conn = DriverManager.getConnection(url, username, password)) {

            Statement stat = conn.createStatement();
            rs = stat.executeQuery("SELECT * FROM staffacc");
            rsmd = rs.getMetaData();
            
            accountsAndOrders.getStaffAccs().clear();
            
            while(rs.next()) {
                accountsAndOrders.addStaff(new Account(rs.getString(2), rs.getString(3), rs.getString(4)));
                numAccs++;
            }
            
            rs = stat.executeQuery("SELECT * FROM customeracc");
            rsmd = rs.getMetaData();
            
            accountsAndOrders.getCustomerAccs().clear();
            
            while(rs.next()) {
                accountsAndOrders.addCustomer(new CustomerAccount(rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)));
                numCAccs++;
            }
            
        } catch (Exception ex) {
            System.out.println("Connection failed..");
            System.out.println(ex);
        }
    }
    
    public static int getNumAccs() {
        return numAccs;
    }
    
    public static void setNumAccs(int num) {
        numAccs = num;
    }
    
    public static int getNumCAccs() {
        return numCAccs;
    }
    
    public static void setNumCAccs(int num) {
        numCAccs = num;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        StaffLoginTxt = new javax.swing.JTextField();
        UserIDTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        lockIcon = new javax.swing.JLabel();
        pizzaIcon = new javax.swing.JLabel();
        loginError = new javax.swing.JTextField();
        Menu = new javax.swing.JMenuBar();
        modeSwitch = new javax.swing.JMenu();
        ManagerMode = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setBackground(new java.awt.Color(204, 204, 255));
        loginPanel.setPreferredSize(new java.awt.Dimension(856, 527));

        StaffLoginTxt.setEditable(false);
        StaffLoginTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        StaffLoginTxt.setText("STAFF LOGIN");
        StaffLoginTxt.setSelectionColor(new java.awt.Color(204, 102, 0));

        UserIDTextField.setText("User ID...");

        PasswordTextField.setText("Password...");

        goButton.setText("GO");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/userIcon.png"))); // NOI18N

        lockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/lockIcon.png"))); // NOI18N

        pizzaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/pizza.png"))); // NOI18N

        loginError.setEditable(false);
        loginError.setBackground(new java.awt.Color(204, 204, 255));
        loginError.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        loginError.setForeground(new java.awt.Color(204, 0, 0));
        loginError.setText("Invalid user ID or password. Please try again.");
        loginError.setBorder(null);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userIcon)
                            .addComponent(lockIcon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(StaffLoginTxt)
                                        .addComponent(UserIDTextField)
                                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addComponent(pizzaIcon)
                                .addGap(52, 52, 52)))))
                .addGap(302, 302, 302))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(pizzaIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StaffLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lockIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        modeSwitch.setText("Mode");

        ManagerMode.setText("Manager Mode");
        ManagerMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerModeActionPerformed(evt);
            }
        });
        modeSwitch.add(ManagerMode);

        Menu.add(modeSwitch);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManagerModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerModeActionPerformed
        managerLoginPage managerMode = new managerLoginPage(); //makes a new managerLoginPage frame
        managerMode.setVisible(true); //sets the new frame visible
        dispose(); //closes this current frame (loginPage) after opening managerLoginPage
    }//GEN-LAST:event_ManagerModeActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
       userIndex = accountsAndOrders.findStaffAccount(UserIDTextField.getText(), PasswordTextField.getText());
        
        if(userIndex == -1) {
           loginError.setVisible(true);
           revalidate();
       } else {
           staffMain sMain = new staffMain();
           sMain.setVisible(true);
           dispose();
       }
    }//GEN-LAST:event_goButtonActionPerformed
    
    public static int getUserIndex() {
        return userIndex;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }
    
    private static int userIndex;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ManagerMode;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField StaffLoginTxt;
    private javax.swing.JTextField UserIDTextField;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel lockIcon;
    private javax.swing.JTextField loginError;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JMenu modeSwitch;
    private javax.swing.JLabel pizzaIcon;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
