package pizza.cashier.interference;


import SQLinfo.Information;
import information.Account;
import information.accountsAndOrders;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

public class managerLoginPage extends javax.swing.JFrame {

    private static int loginAcc;
    static ResultSet rs;
    static ResultSetMetaData rsmd;
    /**
     * Creates new form loginPage
     */
    public managerLoginPage() {
        connectDB(Information.getUrlSQL(), Information.getUsernameSQL(), Information.getPasswordSQL());
        initComponents();
        loginError.setVisible(false); //that way the error isn't just always seen from the beginning, yk?
    }
    
    public static void connectDB(String url, String username, String password) {
        try ( Connection conn = DriverManager.getConnection(url, username, password)) {

            Statement stat = conn.createStatement();
            rs = stat.executeQuery("SELECT * FROM manageracc");
            rsmd = rs.getMetaData();
            
            while(rs.next()) {
                accountsAndOrders.setManagerAcc(new Account(rs.getString(2), rs.getString(3)));
            }

        } catch (Exception ex) {
            System.out.println("Connection failed..");
            System.out.println(ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        StaffLoginTxt = new javax.swing.JTextField();
        UserIDTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JTextField();
        goButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        lockIcon = new javax.swing.JLabel();
        pizzaIcon = new javax.swing.JLabel();
        loginError = new javax.swing.JTextField();
        Menu = new javax.swing.JMenuBar();
        modeSwitch = new javax.swing.JMenu();
        StaffMode = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loginPanel.setBackground(new java.awt.Color(204, 204, 255));

        StaffLoginTxt.setEditable(false);
        StaffLoginTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        StaffLoginTxt.setText("MANAGER MODE");
        StaffLoginTxt.setSelectionColor(new java.awt.Color(204, 102, 0));
        StaffLoginTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffLoginTxtActionPerformed(evt);
            }
        });

        UserIDTextField.setText("User ID...");

        PasswordTextField.setText("Password...");

        goButton.setText("GO");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/userIcon.png"))); // NOI18N

        lockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/lockIcon.png"))); // NOI18N

        pizzaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza/cashier/interference/images/pizza2.png"))); // NOI18N

        loginError.setEditable(false);
        loginError.setBackground(new java.awt.Color(204, 204, 255));
        loginError.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        loginError.setForeground(new java.awt.Color(204, 0, 0));
        loginError.setText("Invalid user ID or password. Please try again.");
        loginError.setBorder(null);

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(pizzaIcon))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lockIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(StaffLoginTxt)
                                        .addComponent(UserIDTextField)
                                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(281, 281, 281))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(loginError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(pizzaIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StaffLoginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lockIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );

        modeSwitch.setText("Mode");

        StaffMode.setText("Staff Mode");
        StaffMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffModeActionPerformed(evt);
            }
        });
        modeSwitch.add(StaffMode);

        Menu.add(modeSwitch);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StaffLoginTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffLoginTxtActionPerformed
    }//GEN-LAST:event_StaffLoginTxtActionPerformed

    private void StaffModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffModeActionPerformed
        // TODO add your handling code here:
        loginPage staffMode = new loginPage(); //makes a new loginPage frame
        staffMode.setVisible(true); //sets the new frame visible
        dispose(); //closes this current frame (managerLoginPage) after opening loginPage
    }//GEN-LAST:event_StaffModeActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        if(accountsAndOrders.isManagerAccount(UserIDTextField.getText(), PasswordTextField.getText()) == false) {
            loginError.setVisible(true);
            revalidate();
        } else {
            managerMain mMain = new managerMain();
            mMain.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_goButtonActionPerformed
    
    public static int getLoginAcc() {
        return loginAcc;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JTextField PasswordTextField;
    private javax.swing.JTextField StaffLoginTxt;
    private javax.swing.JMenuItem StaffMode;
    private javax.swing.JTextField UserIDTextField;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel lockIcon;
    private javax.swing.JTextField loginError;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JMenu modeSwitch;
    private javax.swing.JLabel pizzaIcon;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
